-- ===========================
-- Qwew Chat initial db schema
-- ===========================

-- 1. users
CREATE TABLE IF NOT EXISTS users (
    id              BIGSERIAL PRIMARY KEY,
    username        VARCHAR(50) UNIQUE NOT NULL,
    password_hash   TEXT NOT NULL,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    last_seen_at    TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. single-use invites
CREATE TABLE IF NOT EXISTS invites (
    id              BIGSERIAL PRIMARY KEY,
    code            VARCHAR(20) UNIQUE NOT NULL,
    created_by      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    used_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    used_at         TIMESTAMPTZ,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expires_at      TIMESTAMPTZ
);

-- 3. dms
CREATE TABLE IF NOT EXISTS conversations (
    id              BIGSERIAL PRIMARY KEY,
    user1_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user2_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    -- ensure no duplicate dms
    UNIQUE(user1_id, user2_id)
);

-- 4. messages
CREATE TABLE IF NOT EXISTS messages (
    id              BIGSERIAL PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    sender_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content         TEXT NOT NULL,
    max_length      INTEGER DEFAULT 2000,
    created_at      TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    CONSTRAINT content_length CHECK (LENGTH(content) <= 2000)
);

-- 5. that "read" checkmark. receipt or something
CREATE TABLE IF NOT EXISTS read_receipts (
    id              BIGSERIAL PRIMARY KEY,
    message_id      BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    read_at         TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    
    UNIQUE(message_id, user_id)   -- one receipt per user per message
);

-- =================
-- indexes of course
-- =================

-- fast user lookup by username
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- fast lookup of conversations for a user
CREATE INDEX IF NOT EXISTS idx_conversations_user1 ON conversations(user1_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user2 ON conversations(user2_id);

-- fast message retrieval in a conversation
CREATE INDEX IF NOT EXISTS idx_messages_conversation ON messages(conversation_id, created_at);

-- fast read receipt lookup
CREATE INDEX IF NOT EXISTS idx_read_receipts_message ON read_receipts(message_id);
CREATE INDEX IF NOT EXISTS idx_read_receipts_user ON read_receipts(user_id);

-- =================================================================
-- haven't used comments why don't i learn something useful for once
-- =================================================================

COMMENT ON TABLE users IS 'Stores registered users';
COMMENT ON TABLE invites IS 'Single-use invite codes generated by users';
COMMENT ON TABLE conversations IS '1-on-1 private conversations between two users';
COMMENT ON TABLE messages IS 'All chat messages';
COMMENT ON TABLE read_receipts IS 'Tracks which users have read which messages';
